 CREATE TABLE BOOKS (
 	ID SERIAL PRIMARY KEY,
 	TITLE VARCHAR(100) NOT NULL,
 	AUTHOR VARCHAR(100) NOT NULL,
 	PUBLISHED_DATE DATE,
 	ISBN VARCHAR(20) UNIQUE
 );
 CREATE TABLE USERS (
 	ID SERIAL PRIMARY KEY,
 	USERNAME VARCHAR(50) UNIQUE NOT NULL,
 	PASSWORD VARCHAR(100) NOT NULL
 )

